#!/bin/bash

set -e

function always_chronyd() {
    while true; do
        chronyd -n || true
        sleep 1
    done
}

# Prevent OOM killing
echo -1000 > /proc/self/oom_score_adj

always_chronyd &

setcap 'cap_net_raw+ep' /bin/ping
chown root:user /usr/bin/tcpdump
chmod 750 /usr/bin/tcpdump
setcap 'cap_net_raw,cap_net_admin+eip' /usr/bin/tcpdump

ulimit -u 300

sysctl net.ipv6.conf.all.disable_ipv6=1
sysctl net.ipv6.conf.default.disable_ipv6=1
ip link set lo up

#PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin /homegw-init &
#exec /bin/bash

set +e
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin /homegw-init
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin /homegw-init emergency-kexec
